on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-22.04
    steps:
      - run: mkdir -p ~/.ssh
      - run: echo "${{ secrets.KEY}}" > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: ssh -i ~/.ssh/id_rsa -vvv root@120.79.62.193
      - run: cd ~
      - run: mkdir haha
