on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: "22"
      # - run: npm install

      - run: mkdir -p ~/.ssh
      - run: echo "${{ secrets.KEY}}" > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: ssh-keyscan -p 22 ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - run: rsync -avz -e "ssh -i ~/.ssh/id_rsa" --exclude 'node_modules' ./ root@${{secrets.HOST}}:~/project
      - run: |
          ssh -i ~/.ssh/id_rsa root@${{secrets.HOST}} ''
